name: webpush_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: 'rinukkusu' <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  pointycastle: '0.10.0+5'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
